"""Markdown Migration Guide builder."""

from __future__ import annotations

from app.schemas.diff import ChangeClassification, DiffResult


def build_migration_guide(result: DiffResult, title: str = "APIDrift Migration Guide") -> str:
    lines: list[str] = [
        f"# {title}",
        "",
        f"_Input kind:_ `{result.input_kind.value}`",
        "",
        "## Summary",
        "",
        f"| Total | Breaking | Non-breaking | Deprecation |",
        f"| ---: | ---: | ---: | ---: |",
        (
            f"| {result.summary.total} | {result.summary.breaking} | "
            f"{result.summary.non_breaking} | {result.summary.deprecation} |"
        ),
        "",
    ]

    if result.warnings:
        lines.append("## Warnings")
        lines.append("")
        for warning in result.warnings:
            lines.append(f"- {warning}")
        lines.append("")

    grouped = {
        ChangeClassification.BREAKING: [],
        ChangeClassification.DEPRECATION: [],
        ChangeClassification.NON_BREAKING: [],
    }
    for change in result.changes:
        grouped[change.classification].append(change)

    for classification, heading in (
        (ChangeClassification.BREAKING, "Breaking changes"),
        (ChangeClassification.DEPRECATION, "Deprecations"),
        (ChangeClassification.NON_BREAKING, "Non-breaking changes"),
    ):
        items = grouped[classification]
        lines.append(f"## {heading}")
        lines.append("")
        if not items:
            lines.append("_None._")
            lines.append("")
            continue
        for item in items:
            lines.append(f"### `{item.id}` — {item.path}")
            lines.append("")
            lines.append(f"- **Kind:** `{item.kind.value}`")
            lines.append(f"- **Severity:** `{item.severity.value}`")
            lines.append(f"- **Summary:** {item.summary}")
            if item.before_value is not None:
                lines.append(f"- **Before:** `{item.before_value!r}`")
            if item.after_value is not None:
                lines.append(f"- **After:** `{item.after_value!r}`")
            lines.append("")
            lines.append("**How to fix:** review dependent clients for this path and apply the snippets below.")
            lines.append("")

    if result.snippets:
        lines.append("## Migration snippets")
        lines.append("")
        for snippet in result.snippets:
            lines.append(f"### {snippet.title} (`{snippet.language.value}`)")
            lines.append("")
            lines.append(f"```{snippet.language.value}")
            lines.append(snippet.code)
            lines.append("```")
            lines.append("")

    lines.append("---")
    lines.append("_Generated by APIDrift_")
    lines.append("")
    return "\n".join(lines)
